cluster: smq
broker: f7637a07-a081-42d0-bd56-6643b4ee522b
name: node01
worker: 4096
host: 0.0.0.0
port: 1883
tls:
  enable: false
  verify: false
  cert: ssl/server/cert.pem
  key: ssl/server/key.pem
etcd:
  endpoints:
    - 127.0.0.1:2379
http:
  enable: true
  host: 0.0.0.0
  port: 8888
bridge:
  enable: false
  type: kafka
  kafka:
    addr:
      - 127.0.0.1:9092
notify:
  enable: false
  type: grpc
  server: 127.0.0.1:9999
auth:
  enable: false
acl:
  enable: false
log:
  level: info
